"""empty message

Revision ID: 21ed5ef313b
Revises: 5527454db77
Create Date: 2015-11-12 21:54:18.721024

"""

# revision identifiers, used by Alembic.
revision = '21ed5ef313b'
down_revision = '5527454db77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
