"""empty message

Revision ID: 52df47aba88
Revises: 1971457e801
Create Date: 2015-11-12 15:06:01.122179

"""

# revision identifiers, used by Alembic.
revision = '52df47aba88'
down_revision = '1971457e801'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
